ALTER TABLE "space" ADD CONSTRAINT "fk_space_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "space" ADD CONSTRAINT "uq_space_workspace_id_slug" UNIQUE ("workspace_id", "slug");
ALTER TABLE "space_defaults" ADD CONSTRAINT "fk_space_defaults_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "space_defaults" ADD CONSTRAINT "fk_space_defaults_workspace_id_space_id" FOREIGN KEY ("workspace_id", "space_id") REFERENCES "space" ("workspace_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "space_defaults" ADD CONSTRAINT "uq_space_defaults_workspace_id_space_id" UNIQUE ("workspace_id", "space_id");
ALTER TABLE "user" ADD CONSTRAINT "fk_user_last_workspace_id" FOREIGN KEY ("last_workspace_id") REFERENCES "workspace" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "membership" ADD CONSTRAINT "fk_membership_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "membership" ADD CONSTRAINT "fk_membership_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "membership" ADD CONSTRAINT "uq_membership_workspace_id_user_id" UNIQUE ("workspace_id", "user_id");
ALTER TABLE "workspace" ADD CONSTRAINT "fk_workspace_owner_id" FOREIGN KEY ("owner_id") REFERENCES "user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "doc" ADD CONSTRAINT "fk_doc_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc" ADD CONSTRAINT "fk_doc_workspace_id_space_id" FOREIGN KEY ("workspace_id", "space_id") REFERENCES "space" ("workspace_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc" ADD CONSTRAINT "fk_doc_workspace_id_current_revision_id" FOREIGN KEY ("workspace_id", "current_revision_id") REFERENCES "revision" ("workspace_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "doc" ADD CONSTRAINT "uq_doc_workspace_id_space_id_slug" UNIQUE ("workspace_id", "space_id", "slug");
ALTER TABLE "revision" ADD CONSTRAINT "fk_revision_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "revision" ADD CONSTRAINT "fk_revision_workspace_id_doc_id" FOREIGN KEY ("workspace_id", "doc_id") REFERENCES "doc" ("workspace_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "revision" ADD CONSTRAINT "fk_revision_author_id" FOREIGN KEY ("author_id") REFERENCES "user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "revision" ADD CONSTRAINT "fk_revision_workspace_id_parent_revision_id" FOREIGN KEY ("workspace_id", "parent_revision_id") REFERENCES "revision" ("workspace_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "totp_secret" ADD CONSTRAINT "fk_totp_secret_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "oauth_identity" ADD CONSTRAINT "fk_oauth_identity_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "oauth_identity" ADD CONSTRAINT "uq_oauth_identity_provider_provider_user_id" UNIQUE ("provider", "provider_user_id");
ALTER TABLE "recovery_code" ADD CONSTRAINT "fk_recovery_code_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "recovery_code" ADD CONSTRAINT "uq_recovery_code_user_id_code_hash" UNIQUE ("user_id", "code_hash");
ALTER TABLE "session" ADD CONSTRAINT "fk_session_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
