CREATE UNIQUE INDEX IF NOT EXISTS "idx_space_workspace_id_slug_unique" ON "space" ("workspace_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_space_defaults_workspace_id_space_id_unique" ON "space_defaults" ("workspace_id", "space_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_user_email_unique" ON "user" ("email");
CREATE INDEX IF NOT EXISTS "idx_user_last_workspace_id" ON "user" ("last_workspace_id");
CREATE INDEX IF NOT EXISTS "idx_membership_user_id" ON "membership" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_membership_workspace_id_user_id_unique" ON "membership" ("workspace_id", "user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_workspace_slug_unique" ON "workspace" ("slug");
CREATE INDEX IF NOT EXISTS "idx_workspace_owner_id" ON "workspace" ("owner_id");
CREATE INDEX IF NOT EXISTS "idx_doc_workspace_id_space_id" ON "doc" ("workspace_id", "space_id");
CREATE INDEX IF NOT EXISTS "idx_doc_workspace_id_current_revision_id" ON "doc" ("workspace_id", "current_revision_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_doc_workspace_id_space_id_slug_unique" ON "doc" ("workspace_id", "space_id", "slug");
CREATE INDEX IF NOT EXISTS "idx_revision_workspace_id_doc_id" ON "revision" ("workspace_id", "doc_id");
CREATE INDEX IF NOT EXISTS "idx_revision_author_id" ON "revision" ("author_id");
CREATE INDEX IF NOT EXISTS "idx_revision_workspace_id_parent_revision_id" ON "revision" ("workspace_id", "parent_revision_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_totp_secret_user_id_unique" ON "totp_secret" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_magic_link_email" ON "magic_link" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_magic_link_token_hash_unique" ON "magic_link" ("token_hash");
CREATE INDEX IF NOT EXISTS "idx_oauth_identity_user_id" ON "oauth_identity" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_oauth_identity_provider_provider_user_id_unique" ON "oauth_identity" ("provider", "provider_user_id");
CREATE INDEX IF NOT EXISTS "idx_recovery_code_user_id" ON "recovery_code" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_recovery_code_user_id_code_hash_unique" ON "recovery_code" ("user_id", "code_hash");
CREATE INDEX IF NOT EXISTS "idx_session_user_id" ON "session" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_session_cookie_hash_unique" ON "session" ("cookie_hash");
CREATE INDEX IF NOT EXISTS "idx_login_attempt_email" ON "login_attempt" ("email");
CREATE INDEX IF NOT EXISTS "idx_login_attempt_ip" ON "login_attempt" ("ip");
